# ansible/roles/webserver/tasks/main.yml
- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Enable nginx from amazon-linux-extras
  ansible.builtin.command: amazon-linux-extras install nginx1 -y

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Create Nginx reverse proxy configuration
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Restart Nginx # This will now find the handler

- name: Copy index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Start and enable Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Set SELinux to allow reverse proxy
  command: setsebool -P httpd_can_network_connect 1
  ignore_errors: true
