# ansible/roles/appserver/tasks/main.yml
- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

# DEFINITIVE FIX: Enable a modern version of PHP to ensure MySQL 8 compatibility.
- name: Enable PHP 8.2 from amazon-linux-extras
  ansible.builtin.command: amazon-linux-extras install php8.2 -y

- name: Install Apache (httpd), PHP, and MySQL driver
  ansible.builtin.yum:
    name:
      - httpd
      - php
      - php-mysqlnd
    state: present

- name: Copy submit.php script
  template:
    src: submit.php.j2
    dest: /var/www/html/submit.php

- name: Start and enable Apache service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
